name: custom_sizable_text
description: This package is simplifying the text widget and make it flexible and auto sized. By Using auto_size_text allowed text to be auto sized.
version: 1.1.5+4
homepage: https://github.com/ElGenius-developer/custom_sizable_text
repository: https://github.com/ElGenius-developer/custom_sizable_text

environment:
  sdk: ">=3.0.0 <3.19.2"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

